# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Qwen Offline
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Qwen2.5-codex (Offline)
    provider: ollama
    model: qwen2.5-coder:3b
    apiBase: "http://127.0.0.1:11434"
  - uses: ollama/qwen2.5-coder:3b

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: ollama/memory-mcp
